/*
 * @(#)ProductNames.java
 *
 * Copyright 2002 - 2005 Software Inc. All rights reserved.
 */
package com.element.plaf;

/**
 * 组件名称列表
 */
public interface ProductNames {
	int PRODUCT_COMMON = 0;
	int PRODUCT_DOCK = 0x1;
	int PRODUCT_COMPONENTS = 0x2;
	int PRODUCT_GRIDS = 0x4;
	int PRODUCT_DIALOGS = 0x8;
	int PRODUCT_ACTION = 0x10;
	int PRODUCT_PIVOT = 0x20;
	int PRODUCT_SHORTCUT = 0x40;
	int PRODUCT_CODE_EDITOR = 0x80;
	int PRODUCT_FEEDREADER = 0x100;
	int PRODUCT_JDAF = 0x200;
	int PRODUCT_DASHBOARD = 0x400;
	int PRODUCT_DATAGRIDS = 0x800;
	int PRODUCT_CHARTS = 0x1000;
	int PRODUCT_GANTT_CHART = 0x2000;
	int PRODUCT_DIFF = 0x4000;
	int PRODUCT_TREEMAP = 0x8000;

	int PRODUCT_PROFESSIONAL_SUITE = PRODUCT_COMMON | PRODUCT_ACTION | PRODUCT_DOCK;
	int PRODUCT_ENTERPRISE_SUITE = PRODUCT_PROFESSIONAL_SUITE | PRODUCT_COMPONENTS | PRODUCT_GRIDS | PRODUCT_DIALOGS;
	int PRODUCT_ULTIMATE_SUITE = PRODUCT_ENTERPRISE_SUITE | PRODUCT_PIVOT | PRODUCT_SHORTCUT | PRODUCT_FEEDREADER | PRODUCT_CODE_EDITOR | PRODUCT_DASHBOARD | PRODUCT_DATAGRIDS | PRODUCT_CHARTS | PRODUCT_GANTT_CHART | PRODUCT_DIFF | PRODUCT_TREEMAP;
	int PRODUCT_SOLUTION = PRODUCT_JDAF;
	int PRODUCT_ALL = 0xFFFF;
}
